## Basic DataFrame

In [1]:
# import the required library
import pandas as pd

In [2]:
# Read a dataset named: 'imdb-top-1000' and show top 5 rows
df = pd.read_csv('Dataset/imdb-top-1000.csv')
df.head(5)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [3]:
# How many movies are in the dataset?
df.shape[0]

1000

In [4]:
df.shape[1]

10

In [10]:
# What are the column names?
df.columns

Index(['Series_Title', 'Released_Year', 'Runtime', 'Genre', 'IMDB_Rating',
       'Director', 'Star1', 'No_of_Votes', 'Gross', 'Metascore'],
      dtype='str')

In [13]:
df.dtypes

Series_Title         str
Released_Year        str
Runtime            int64
Genre                str
IMDB_Rating      float64
Director             str
Star1                str
No_of_Votes        int64
Gross            float64
Metascore        float64
dtype: object

In [12]:
# Provide dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   str
 1   Released_Year  1000 non-null   str
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   str
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   str
 6   Star1          1000 non-null   str
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), str(5)
memory usage: 78.3 KB

In [9]:
# What about statistical summary
df.describe()

           Runtime  IMDB_Rating   No_of_Votes         Gross   Metascore
count  1000.000000  1000.000000  1.000000e+03  1.000000e+03  843.000000
mean    122.891000     7.949300  2.736929e+05  1.282781e+08   77.971530
std      28.093671     0.275491  3.273727e+05  2.011110e+08   12.376099
min      45.000000     7.600000  2.508800e+04  1.305000e+03   28.000000
25%     103.000000     7.700000  5.552625e+04  5.012919e+06   70.000000
50%     119.000000     7.900000  1.385485e+05  3.953432e+07   79.000000
75%     137.000000     8.100000  3.741612e+05  1.615997e+08   87.000000
max     321.000000     9.300000  2.343110e+06  9.366622e+08  100.000000

In [15]:
# Check if there is any missing values
df.isna()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

In [18]:
# Fill the missing value with the mean of that particular column
df['Metascore'] = df['Metascore'].fillna(df['Metascore'].mean())

In [12]:
# Show movies with rating above 9

In [14]:
# Show 10 most rated movies

In [16]:
# Show number of movies done by each star

## GroupBy

In [19]:
# Group all data based on "Genre"
genre = df.groupby('Genre')
genre

In [18]:
# groups

In [19]:
# find total number of groups -> len

In [20]:
# find items in each group -> size

In [21]:
# first()/last()/nth() item

In [22]:
# get_group

In [23]:
# Compute mean for all numerical columns for each genre

In [24]:
# Find top 3 genre by total earning

In [1]:
# Find the genre with highest avg imdb ratings (Task)

In [26]:
# Find the most earning actor-director combo

In [27]:
# find the highest rated movie of each genre (Hint -> idxmax())

## Merging and Concatenation

In [28]:
# Read datasets
courses = pd.read_csv("courses.csv")
nov = pd.read_csv("reg-month1.csv")
dec = pd.read_csv("reg-month2.csv")
students = pd.read_csv("students.csv")

In [29]:
# Concat 'nov' and 'dec' data and name it 'registration' or 'reg'

In [31]:
# inner join (reg and students)

In [32]:
# right join

In [33]:
# left join

In [34]:
# outer join

In [35]:
# Find total revenue generated

In [37]:
# Print the registration table 
# cols -> name -> course -> price

In [38]:
# Plot bar chart for revenue/course (revenue per course)

In [39]:
# Print student name -> partner name for all enrolled students
# self join

In [40]:
# Find top 3 students who did most number of enrollments

*Happy Coding 🎉🎉*